services:
  db:
    image: postgres:16
    container_name: postgres
    expose:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - backend
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - .env
    depends_on: 
      - db
      - redis
    restart: always
    volumes:
      - db-data:/data

  redis:
    container_name: redis
    image: redis
    networks:
      - backend
    expose:
      - 6379:6379
    restart: always
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend
    restart: always

volumes:
  db-data:

  pgdata:
      
networks:
  backend:
    driver: bridge
