---
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - backend
  backend:
    container_name: backend
    build: backend/Dockerfile
  env_file:
    - .env
  networks:
  - backend
  depends_on:
    - db

volumes:
  pgdata:
    driver: local
      
networks:
  backend:
    driver: bridge