---
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - backend
    restart: always
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    networks:
    - backend
    env_file:
      - .env
    depends_on: 
    - db
    restart: always

volumes:
  pgdata:
    driver: local
      
networks:
  backend:
    driver: bridge