FROM node:alpine AS build
COPY ./app /app
WORKDIR /app
RUN npm install && npm run build

FROM --platform=linux/amd64 nginx:alpine AS prod
COPY nginx-prod.conf /etc/nginx/
COPY  --from=build /app/dist /app
CMD ["nginx", "-g", "daemon off;"]