FROM --platform=linux/amd64 node:alpine AS build
COPY ./app /app
WORKDIR /app
RUN npm install && npm run build

FROM --platform=linux/arm64 arm64v8/nginx:alpine AS prod
COPY nginx-prod.conf /etc/nginx/nginx.conf
COPY  --from=build /app/dist /app
CMD ["nginx", "-g", "daemon off;"]