# Generated by Django 5.0.3 on 2024-03-14 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pong',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pong',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pong',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
