# Generated by Django 5.0.3 on 2024-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_pong_players_pong_player1_pong_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='max_score',
            field=models.IntegerField(default=10),
        ),
    ]
