# Generated by Django 5.0.3 on 2024-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_points',
            field=models.IntegerField(default=10),
        ),
    ]
