FROM python:3.12-alpine as builder
RUN apk add --no-cache postgresql-dev gcc python3-dev musl-dev libffi-dev

RUN pip install poetry==1.7.1

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /data/backend
RUN export PATH=/data/backend:$PATH
#ENTRYPOINT [ "sleep", "infinity" ]
ENTRYPOINT [ "./entrypoint.sh" ]