# Generated by Django 5.0.3 on 2024-04-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
