# Generated by Django 5.0.3 on 2024-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='category',
            field=models.CharField(default='dm', max_length=255),
        ),
    ]
