# Generated by Django 5.0.3 on 2024-03-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='category',
        ),
    ]
