# Generated by Django 5.0.2 on 2024-03-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
