# Generated by Django 5.0.6 on 2024-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
