# Generated by Django 5.0.2 on 2024-03-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_2fa_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_active',
            field=models.BooleanField(default=False),
        ),
    ]
