apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  oauth-app-secret: {{ .Values.backend.oauth_secret | b64enc }}
  oauth-app-uid: {{ .Values.backend.oauth_uid | b64enc }}
  jwt-secret: {{ .Values.backend.jwt_secret | default (randAlpha 50) | b64enc }}
  fernet-secret: {{ .Values.backend.fernet_secret | default (b64enc (randAlpha 32)) | b64enc }}
  django-secret-key: {{ .Values.backend.django_secret_key | default (randAlphaNum 50) | b64enc }}
  user-default-pass: {{ .Values.backend.user_default_pass | default (randAlphaNum 14) | b64enc }}
