apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.backend.hostname }}
  name: {{ .Values.backend.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: {{ .Values.backend.hostname }}
status: {}
