apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  oauth-app-secret: {{ .Values.backend.oauth_secret | b64enc }}
  oauth-app-uid: {{ .Values.backend.oauth_uid | b64enc }}
  jwt-secret: {{ .Values.backend.jwt_secret | b64enc }}
  fernet-secret: {{ .Values.backend.fernet_secret | b64enc }}
  django-secret-key: {{ .Values.backend.django_secret_key | b64enc }}
  user-default-pass: {{ .Values.backend.user_default_pass | b64enc }}
