apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.frontend.hostname }}
  name: {{ .Values.frontend.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: {{ .Values.frontend.hostname }}

