apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.redis.hostname }}
  name: {{ .Values.redis.hostname }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.redis.port | quote }}
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    io.kompose.service: {{ .Values.redis.hostname }}

