# Generated by Django 5.0.4 on 2024-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('win_streaks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
